# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.FloatField(default=1)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to=b'')),
                ('requirement', models.CharField(max_length=500)),
                ('stock', models.IntegerField()),
                ('limit_per_day', models.IntegerField()),
                ('completed', models.IntegerField(default=0)),
                ('ordered', models.IntegerField(default=0)),
                ('reviewed', models.IntegerField(default=0)),
                ('must_review', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'Ordered'), (2, 'Order Verified'), (3, 'Reviewed'), (4, 'Review Verified')], default=1)),
                ('order_screenshot', models.ImageField(upload_to=b'')),
                ('review_screenshot', models.ImageField(upload_to=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product')),
            ],
        ),
    ]
