# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('view_product', 'Can View Product'),)},
        ),
    ]
