# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20171208_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=mainapp.models.product_user_directory_path),
        ),
    ]
