# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 06:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0007_auto_20171209_2244'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('seller_id', 'name')]),
        ),
    ]
