# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20171209_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='requirement',
            field=models.TextField(max_length=500),
        ),
    ]
