# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20171210_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='requirement',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
