# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20171224_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_link',
            field=models.URLField(blank=True),
        ),
    ]
