# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import mainapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20171225_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amazon_link',
            field=models.URLField(blank=True, max_length=500, validators=[mainapp.validators.AmazonURLValidator(message='Domain must be Amazon')]),
        ),
    ]
