# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-03 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20171225_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='order_screenshot',
            field=models.ImageField(upload_to=mainapp.models.purchase_user_directory_path),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='review_screenshot',
            field=models.ImageField(upload_to=mainapp.models.purchase_user_directory_path),
        ),
    ]
