# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 19:54
from __future__ import unicode_literals

from django.db import migrations
# from django.contrib.auth.models import Group, Permission


def add_group_and_perm(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    seller_group, created = Group.objects.get_or_create(name='seller_group')
    if created:
        add_product_permission = Permission.objects.get(codename='add_product')
        change_product_permission = Permission.objects.get(codename='change_product')
        delete_product_permission = Permission.objects.get(codename='delete_product')
        seller_group.permissions.add(add_product_permission, change_product_permission, delete_product_permission)
        seller_group.save()

    buyer_group, created = Group.objects.get_or_create(name='buyer_group')
    if created:
        view_product_permission = Permission.objects.get(codename='view_product')
        add_purchase_permission = Permission.objects.get(codename='add_purchase')
        buyer_group.permissions.add(view_product_permission, add_purchase_permission)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_group_and_perm),
    ]
